name: AHAT
dataset_path: /Users/kathyxxj/Documents/mrlab/dataset/AHAT
cache_dir: ./logs/cache
test_result_folder: ./test
val_files: ['1.ply', '2.ply'] 
val_label_files: ['1_labels.txt', '2_labels.txt'] 
use_cache: False
num_classes: 2
num_points: 67575