dataset:
  name: AHAT
  dataset_path: /Users/kathyxxj/Documents/mrlab/dataset/AHAT
  cache_dir: ./logs/cache
  test_result_folder: ./test
  val_files: ['1.ply', '2.ply'] 
  val_label_files: ['1_labels.txt', '2_labels.txt'] 
  use_cache: False
  num_classes: 2
  num_points: 67575
  steps_per_epoch_train: 1
  steps_per_epoch_valid: 1
model:
  name: KPFCNN
  ckpt_path: # path/to/your/checkpoint
  KP_extent: 1.0
  KP_influence: linear
  aggregation_mode: sum
  architecture:
  - simple
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb_strided
  - resnetb
  - resnetb_strided
  - resnetb
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  - nearest_upsample
  - unary
  augment_color: 0.8
  augment_noise: 0.001
  augment_rotation: vertical
  augment_scale_anisotropic: true
  augment_scale_max: 1.2
  augment_scale_min: 0.8
  augment_symmetries:
  - true
  - false
  - false
  batch_limit: 80000
  batch_norm_momentum: 0.98
  batcher: ConcatBatcher
  conv_radius: 2.5
  deform_fitting_mode: point2point
  deform_fitting_power: 1.0
  deform_radius: 6.0
  density_parameter: 5.0
  first_features_dim: 128
  first_subsampling_dl: 0.04
  fixed_kernel_points: center
  ignored_label_inds: []
  in_features_dim: 2
  in_points_dim: 3
  in_radius: 1.5
  lbl_values: [0, 1]
  min_in_points: 20000
  max_in_points: 70000
  modulated: false
  num_classes: 2
  num_kernel_points: 15
  num_layers: 5
  repulse_extent: 1.2
  use_batch_norm: true
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  momentum: 0.98
  batch_size: 2
  learning_rate: 0.01
  lr_decays: 0.98477
  deform_lr_factor: 0.1
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 5
  scheduler_gamma: 0.95
  test_batch_size: 2
  train_sum_dir: train_log
  val_batch_size: 2
  weight_decay: 0.001
